# Generated by Django 5.2.8 on 2025-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nrc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('dui', models.CharField(blank=True, max_length=20, null=True)),
                ('es_importador', models.BooleanField(default=False)),
                ('email_facturas', models.EmailField(blank=True, max_length=254, null=True)),
                ('clave_correo', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_sync', models.TimeField(default='03:00:00')),
            ],
        ),
    ]
