# Generated by Django 5.2.8 on 2025-11-19 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(default='03', max_length=2)),
                ('codigo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc_proveedor', models.CharField(max_length=20)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('monto_gravado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clasificacion_1', models.CharField(default='Gravada', max_length=50)),
                ('clasificacion_2', models.CharField(blank=True, max_length=50)),
                ('clasificacion_3', models.CharField(blank=True, max_length=50)),
                ('periodo_aplicado', models.CharField(max_length=7)),
                ('estado', models.CharField(default='Registrado', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='api.cliente')),
            ],
        ),
    ]
