# Generated by Django 5.2.8 on 2025-11-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_venta', models.CharField(choices=[('CF', 'Consumidor Final'), ('CCF', 'Contribuyente')], max_length=10)),
                ('codigo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_control_desde', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_control_hasta', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('nrc_receptor', models.CharField(blank=True, max_length=20, null=True)),
                ('venta_gravada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('venta_exenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('venta_no_sujeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('debito_fiscal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva_retenido_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva_retenido_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('periodo_aplicado', models.CharField(max_length=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='api.cliente')),
            ],
        ),
    ]
