# Generated by Django 5.2.8 on 2025-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigo_generacion',
            new_name='numero_resolucion',
        ),
        migrations.AddField(
            model_name='venta',
            name='clase_documento',
            field=models.CharField(choices=[('1', 'Impreso por Imprenta'), ('2', 'Formulario Único'), ('3', 'Ticket / Máquina Registradora'), ('4', 'Documento Electrónico (DTE)')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_control_dte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='serie_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
