# Generated by Django 5.2.8 on 2025-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_codigo_generacion_venta_numero_resolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='clasificacion_venta',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_ingreso',
            field=models.CharField(default='3', max_length=20),
        ),
    ]
