# Generated by Django 5.2.8 on 2025-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_venta_clasificacion_venta_venta_tipo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_formulario_unico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
