# Generated by Django 5.2.8 on 2025-11-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_venta_numero_formulario_unico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('periodo_aplicado', models.CharField(max_length=7)),
                ('tipo_retencion', models.CharField(choices=[('1', 'Retención IVA 1% (Cliente)'), ('2', 'Retención Tarjeta (Banco)')], default='1', max_length=2)),
                ('codigo_generacion', models.CharField(max_length=100)),
                ('sello_recepcion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_emisor', models.CharField(max_length=200)),
                ('nrc_emisor', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_sujeto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_retenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='api.cliente')),
            ],
        ),
    ]
