# Generated by Django 5.2.8 on 2025-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='nit_emisor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retencion',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retencion',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='tipo_retencion',
            field=models.CharField(choices=[('161', 'Retención Tarjeta (Anexo 6)'), ('162', 'Retención IVA 1% (Anexo 7)')], default='162', max_length=3),
        ),
    ]
