# Generated by Django 5.2.8 on 2025-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_retencion_nit_emisor_retencion_numero_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='numero_control_dte',
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_formulario_unico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='serie_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
