# Generated by Django 5.2.8 on 2025-12-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_venta_numero_control_dte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='monto_percepcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
